"""create invoice items table

Revision ID: 2201c977521a
Revises: d8a36553a067
Create Date: 2025-12-28 16:04:20.160119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2201c977521a'
down_revision: Union[str, Sequence[str], None] = 'd8a36553a067'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('clients', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('clients', sa.Column('address', sa.String(length=500), nullable=True))
    op.add_column('clients', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('clients', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('clients', sa.Column('postal_code', sa.String(length=20), nullable=True))
    op.alter_column('clients', 'language',
               existing_type=postgresql.ENUM('EN', 'DE', 'ES', name='language'),
               type_=sa.Enum('EN', 'DE', 'ES', name='language'),
               existing_nullable=False)
    op.alter_column('invoices', 'status',
               existing_type=postgresql.ENUM('PENDING', 'PAID', 'CANCELED', name='status'),
               type_=sa.Enum('PENDING', 'PAID', 'CANCELED', name='status'),
               existing_nullable=False)
    op.add_column('products', sa.Column('stock', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.alter_column('products', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('products', 'is_active')
    op.drop_column('products', 'stock')
    op.alter_column('invoices', 'status',
               existing_type=sa.Enum('PENDING', 'PAID', 'CANCELED', name='invoice_status'),
               type_=postgresql.ENUM('PENDING', 'PAID', 'CANCELED', name='status'),
               existing_nullable=False)
    op.alter_column('clients', 'language',
               existing_type=sa.Enum('EN', 'DE', 'ES', name='client_language'),
               type_=postgresql.ENUM('EN', 'DE', 'ES', name='language'),
               existing_nullable=False)
    op.drop_column('clients', 'postal_code')
    op.drop_column('clients', 'country')
    op.drop_column('clients', 'city')
    op.drop_column('clients', 'address')
    op.drop_column('clients', 'phone')
    op.drop_column('clients', 'email')
    # ### end Alembic commands ###
